language: node_js
node_js:
- '6'
before_deploy:
- openssl aes-256-cbc -K $encrypted_f4f02678f555_key -iv $encrypted_f4f02678f555_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
dd:
  secure: gcs8B9dD/2PjzbaDk7QP07Au7OI0NCMFA13Ij4b5RGxwgfdctM9tTllaWx6at4gA7JXFMnSR0ZZOvHa7QhP8398uDa8t0H87yS+v/b+VEpZ2/WLdX+pS1ans32gLkEsnye+y9K3xwcf1ewI6utQWah3a3TEGxGexPcQZ7eWqplRQrElb5ZabsQHyfgTy8k4q28xgTLBJub2A+qnl7QdH7TL7ZxI8Ih0bX8epLukqNoNuYcHbhPa5VyuNpPW1l+dSh8hN99DcAZvmcI2090yGW9Rq0qy/sKN+riZRj/+I2KSwrhrx3F2RxMAc6omgMgB+YxiIEbm6SXeVSrQYrL+mzp+/4+UqtncwZZ6KLEMOcCfxNGV1xtf+dr/ZDlW74ZIgA7zRFNmWvzdaWDhvAhq925Ck9n/MjsOEtlW4xhTTUGC70uOA4zlD27jQAVgDsT3boQIPrwdsCZwrhRNzpnoX4mTaHKRyuL6GnNkVnObu8yFAU2e2CCapRg5b06XbV9LKnVCqk364en6sa1ImvQsLAulzm9sYVcDssa/jSC42jeWsBUXj1vSTUagSZwBSMOxT97P4LdBfaI3YCBYpZg7ktQrO3EX2azjjZd3KK5fUIffGvWoJAh8DfunQ/VKrJcozSFLwEI5r18RKwC3NRmLr1imAgcvrnIVrgApxw+NXiRo=
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR $SSH_PATH
  on:
    branch: master
