language: node_js
node_js:
- '6'

before_deploy:
- openssl aes-256-cbc aes-256-cbc -K $encrypted_f4f02678f555_key -iv $encrypted_f4f02678f555_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa