language: node_js
node_js:
- '6'
cache:
  directories:
  - node_modules

branches:
  only:
  - master

after_success:
- openssl aes-256-cbc -K $encrypted_f4f02678f555_key -iv $encrypted_f4f02678f555_iv
  -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
- ssh $SSH_PATH deploy-adept.sh

env:
  global:
    - CXX=g++-4.8
  matrix:
    - secure: TETjNAxjqmTBmUQq3RaX53R+JJzy2EoKgCLNoxkkK4l48oZZejlBzepfH1wc/39TQj6hjvyXw2Of+DDt6mIM9GT7NWIESzgKYscA1M9eO13Azf5ksDkkudY/zYuDirkJhv5aj4MSp7HrJm4Rzr1pawozVJGAt4DrLH6HvY/Y1uZKvFlV7fK/SiFyvb75kU4Kn/ieuqD2dhpKkHB6NHyaUXlcMwi5KycOqAlbkRijNT00+4loj0j7bC13bQBL2YGVWaxCR2EfGolB/uW+yZfqiYz/nQ5etzzfyDnvZHv7EeYVUrQYLVIzwN1XNwWWT3xJZAstaa36W44qotXP3CjlcDxBqkcYUOww3hY2/Ywrazerpq6s1pDtg+vnCVt9qE7s3wU7zu376NxSDXWK3dO1C1TT8wNLHlbr1MNfpheq/wfANBkpvVpMNPv+36Aym+Xk57gOLy57473QxcQqAPwV0+LBpDbF0qvApyAOHXqCkh9X0vr2d+e/HBwCElx5Pe7Jwl8t4+ekCTgjFqKdmx4VBFyE4lJ3JRCOggyASNkFPEW4rC3881qr8dEfe232jnHIF7z5NlpFP054Xhn3W8lqUoYoopS08RX+4I9EI5Mcft3C5Bg2qq1RUVUYhR4wOgkTPJe7Ywz/mkC9BwKavk7i+L4mqf5PzfTensRDBpbU4Xg=

addons:
  ssh_known_hosts:
    secure: MrQr5rBsNB8ToH5AD09Lg94TrlotCoGdh0xV7WDGtgc0GpEgeJzCTadmRDLxXVDRsNZmqNPrKYBBQ6cFAAmpwHYRjNJwB8nNaTovlufweRCkRclPINUlI4GvuicERVesV7tPML3lLMfIEOwoZz/NwoQqO42xA+pF3xtYy9tOrhvla7yUKvzLlvgGN1u38gzOoLTo4KiaAzI5Q+g3OHaZ1VyYaQazIUzufvPB+1i8R11q0Xz31xpyjgoskRvMn/Ac0ADEbJnlL+OQo/zjkhMIViJOWlXiDrdcUwv6KdeGawITi03tNCF0zk4iyjWa2ZDvA88GiVD2REREVRwKbgjKzlmSj5O0gd8rx2CgS3NzFlBIZ1ISGCgBRx8G9sDHft4QcubwHBJd4/nxJElyp0bzInwl4pRn2eAru/r9ydjFS5LWCICxdvHV4I4EhaAr/a9Vwf7mifT8wmXyFFtCaxM8FIZBF0QzcTI+puT8TxRTkZ5MZz2FK4WzZcvTiCe+XD7N5PNjwUbKf5wjTGFeugAzfz+8qvsdZwbGO8Bp364DBDhcph6vfFfpLc8H71SSiOAbXQVo4gnbC4/3GzSTqenSGdWQqzzxLK6nsU3O0x5K2iqKmtSmBX7xPKEuki5CxtE8hR/eVHkbf62n0ibAMVqZJANX0d8M4Kw6qo85pm5Immo=
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install: false
script: 1